layout_spectrum: 0.3749107
typography_spectrum: 0.440694
color:
  saturation: 0.6870003
  lightness: 0.9199109
  brandStrength: 0.2786288
  rhythmicContrast: 0.0372354
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: Marybirdsong.com
